services:
  db:
    image: postgres:16
    env_file:
      - .env
    container_name: teamfinder_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: teamfinder_web
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_data:/app/media
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  media_data:
